[project]
name = "homequant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anyio>=4.12.1",
    "fastapi>=0.128.8",
    "loguru>=0.7.3",
    "psutil>=7.2.2",
    "pyyaml>=6.0.3",
]
